import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import PrelineScript from '@/app/components/PrelineScript';
import HomeNavbar from '@/app/HomeNavbar';
import { AuthProvider } from '@/app/contexts/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-[100svh] overflow-hidden'>
      <body className={inter.className + ' max-h-full overflow-hidden'}>
        <AuthProvider>
          <HomeNavbar />
          <div className='vp flex h-full w-full flex-col items-center overflow-hidden overflow-y-scroll pt-32'>
            {children}
          </div>
        </AuthProvider>
        <PrelineScript />
      </body>
    </html>
  );
}
